name: Deploy Angular Frontend

on:
  push:
    branches:
      - main # O el nombre de tu rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24' # Ajusta a la versión que uses

      - name: Instalar dependencias
        run: npm ci

      - name: Compilar Angular para producción
        run: npm run build --configuration=production
      - name: Debug - Ver archivos compilados
        run: ls -R dist/
      - name: Desplegar al VPS vía SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/kikhana-web/browser/*" # Ajusta la ruta exacta de tu dist
          target: "/var/www/kikhana/frontend/"
          strip_components: 3 # Esto quita las carpetas "dist/nombre/browser" y deja solo los archivos

      - name: Ajustar permisos en el VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            chown -R www-data:www-data /var/www/kikhana/frontend
            chmod -R 755 /var/www/kikhana/frontend
